// Let goreportcard check us.
// Code generated by gen_version; DO NOT EDIT.

//go:generate go run ./internal/gen/version

package cshargextcap

// SemVersion is the semantic version string of the cshargextcap module.
const SemVersion = "0.9.2"
