name: 'build and release'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3
      - name: Get all git tags
        run: |
          git fetch --prune --unshallow --tags --force
      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # pin@v4
      - name: Install go-winres
        run: |
          go install github.com/tc-hib/go-winres@latest
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7 # pin@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release packetflix-handler.zip
        uses: softprops/action-gh-release@v1
        with:
          files: packaging/macos/packetflix-handler/packetflix-handler.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  archpkgbuildtest:
    runs-on: ubuntu-latest # sic!
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3
      - name: Get all git tags
        run: |
          git fetch --prune --unshallow --tags --force
      - name: Test packaging and testing package
        run: (cd packaging/aur && ./makepackage.sh)
